import { IconName } from './IconName'

const mapping = {
  'arrow-down': require('!!raw-loader!./assets/arrow-down.svg'),
  bars: require('!!raw-loader!./assets/bars.svg'),
  'bars-left': require('!!raw-loader!./assets/bars-left.svg'),
  'bars-right': require('!!raw-loader!./assets/bars-right.svg'),
  calendar: require('!!raw-loader!./assets/calendar.svg'),
  camera: require('!!raw-loader!./assets/camera.svg'),
  chat: require('!!raw-loader!./assets/chat.svg'),
  check: require('!!raw-loader!./assets/check.svg'),
  client: require('!!raw-loader!./assets/client.svg'),
  comment: require('!!raw-loader!./assets/comment.svg'),
  copy: require('!!raw-loader!./assets/copy.svg'),
  cross: require('!!raw-loader!./assets/cross.svg'),
  'delete-circle': require('!!raw-loader!./assets/delete-circle.svg'),
  download: require('!!raw-loader!./assets/download.svg'),
  exclamation: require('!!raw-loader!./assets/exclamation.svg'),
  filter: require('!!raw-loader!./assets/filter.svg'),
  'flash-off': require('!!raw-loader!./assets/flash-off.svg'),
  'flash-on': require('!!raw-loader!./assets/flash-on.svg'),
  gallery: require('!!raw-loader!./assets/gallery.svg'),
  info: require('!!raw-loader!./assets/info.svg'),
  'left-arrow': require('!!raw-loader!./assets/left-arrow.svg'),
  'left-double-arrow': require('!!raw-loader!./assets/left-double-arrow.svg'),
  mail: require('!!raw-loader!./assets/mail.svg'),
  more: require('!!raw-loader!./assets/more.svg'),
  number: require('!!raw-loader!./assets/number.svg'),
  person: require('!!raw-loader!./assets/person.svg'),
  phone: require('!!raw-loader!./assets/phone.svg'),
  ruble: require('!!raw-loader!./assets/ruble.svg'),
  'right-arrow': require('!!raw-loader!./assets/right-arrow.svg'),
  'right-double-arrow': require('!!raw-loader!./assets/right-double-arrow.svg'),
  settings: require('!!raw-loader!./assets/settings.svg'),
  star: require('!!raw-loader!./assets/star.svg'),
  status: require('!!raw-loader!./assets/status.svg'),
  target: require('!!raw-loader!./assets/target.svg'),
  telegram: require('!!raw-loader!./assets/telegram.svg'),
  'trash-can': require('!!raw-loader!./assets/trash-can.svg'),
  url: require('!!raw-loader!./assets/url.svg'),
  viber: require('!!raw-loader!./assets/viber.svg'),
  whatsapp: require('!!raw-loader!./assets/whatsapp.svg'),
}

export const getIconFile = (name: IconName) => mapping[name]
