export type IconName =
  | 'calendar'
  | 'check'
  | 'comment'
  | 'copy'
  | 'cross'
  | 'delete-circle'
  | 'exclamation'
  | 'info'
  | 'left-arrow'
  | 'left-double-arrow'
  | 'phone'
  | 'right-arrow'
  | 'right-double-arrow'
